services:
  onessh:
    depends_on:
      ssh1:
        condition: service_started
      ssh2:
        condition: service_started
  ssh1:
    image: lscr.io/linuxserver/openssh-server:latest
    environment:
      PASSWORD_ACCESS: "true"
      USER_PASSWORD: pass
      USER_NAME: test
      LOG_STDOUT: "true"
    expose:
      - "2222"
  ssh2:
    image: lscr.io/linuxserver/openssh-server:latest
    environment:
      PASSWORD_ACCESS: "true"
      USER_PASSWORD: pass
      USER_NAME: test
      LOG_STDOUT: "true"
    expose:
      - "2222"
