services:
  onessh:
    depends_on:
      ssh1:
        condition: service_started
      ssh2:
        condition: service_started
      ssh-no-tools:
        condition: service_started
  ssh1:
    build:
      context: .
      dockerfile: e2e/Dockerfile.ssh
    image: onessh-ssh-test
    environment:
      PASSWORD_ACCESS: "true"
      USER_PASSWORD: pass
      USER_NAME: test
      LOG_STDOUT: "true"
    expose:
      - "2222"
  ssh2:
    build:
      context: .
      dockerfile: e2e/Dockerfile.ssh
    image: onessh-ssh-test
    environment:
      PASSWORD_ACCESS: "true"
      USER_PASSWORD: pass
      USER_NAME: test
      LOG_STDOUT: "true"
    expose:
      - "2222"
  ssh-no-tools:
    image: lscr.io/linuxserver/openssh-server:latest
    environment:
      PASSWORD_ACCESS: "true"
      USER_PASSWORD: pass
      USER_NAME: test
      LOG_STDOUT: "true"
    expose:
      - "2222"
